const IP_LOCATION_TOKEN = process.env.REACT_APP_IP_LOCATION_TOKEN;
const ONE_MINUTE = 60000;
const MIDNIGHT_WITHOUT_SECONDS = '00:00';

export { IP_LOCATION_TOKEN, ONE_MINUTE, MIDNIGHT_WITHOUT_SECONDS };
