const IP_LOCATION_TOKEN = process.env.REACT_APP_IP_LOCATION_TOKEN;
const ONE_MINUTE = 60000;
const MIDNIGHT_WITHOUT_SECONDS = '00:00';
const DEFAULT_LONDON_LOCATION = {
  city: 'London',
  lng: '	-0.118092',
  lat: '51.509865',
};

export {
  IP_LOCATION_TOKEN,
  ONE_MINUTE,
  MIDNIGHT_WITHOUT_SECONDS,
  DEFAULT_LONDON_LOCATION,
};
